name: Print test results from JUnit XML
inputs:
  files:
    description: Glob pattern matching the files containing test results in JUnit's XML format
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.files }}"
